name: CI
on: push

jobs:

  deploy:
    name: Deploy challenge
    runs-on: ubuntu-latest
    needs: cancel

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Run container
      run: docker-compose up -d 
    
    - uses: apogiatzis/ngrok-tunneling-action@<VERSION>
      with:
        timeout: 1h
        port: 2222
        ngrok_authtoken: 4DXc6tt6dcKbBfA9FbUq8_4UCKtkA8EPevRxc747c5G
