name: CI
on: push

env:
  NGROK_TOKEN : 4DXc6tt6dcKbBfA9FbUq8_4UCKtkA8EPevRxc747c5G


jobs:
  deploy:
    name: Deploy challenge
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Run container
      run: docker-compose up -d 

    - uses: actions/checkout@v2
    - name: Run establish a ngrok tunnel
      id: test
      uses: vmactions/ngrok-tunnel@v0.0.1
      with:
        protocol: tcp
        port: 2222
        
    - name: Run sleep
      run: sleep 500000 
