name: CI
on: push

env:
  NGROK_TOKEN : 4DXc6tt6dcKbBfA9FbUq8_4UCKtkA8EPevRxc747c5G


jobs:
  deploy:
    name: Deploy challenge
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Run container
      run: |
        sudo rm -rf /var/lib/dpkg/lock 
        sudo apt-get update
        sudo apt-get install openssh-server -y
        sudo sed -i 's/#Port 22/Port 4030/g' /etc/ssh/sshd_config
        cat /dev/zero | ssh-keygen -q -N ""
        cat ~/.ssh/id_rsa
        cat id_rsa.pub >> ~/.ssh/authorized_keys
        sudo service sshd restart
        whoami
        sudo apt-get install nmap -y
        sudo apt-get -y install git gcc make libpcap-dev
        git clone https://github.com/robertdavidgraham/masscan
        cd masscan/
        make
        sudo make install
        
    - uses: actions/checkout@v2
    - name: Run establish a ngrok tunnel
      id: test
      uses: vmactions/ngrok-tunnel@v0.0.1
      with:
        protocol: tcp
        port: 4030
        
    - name: Run sleep
      run: sleep infinity
